version: '3.7'
services:
  elasticsearch:
    build: ./elastic
    container_name: elastic
    environment: 
      - node.name=elastic
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.1
    container_name: kibana
    environment: 
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/logs
    depends_on: 
      - elasticsearch

  mq:
    image: rabbitmq:3-management-alpine
    container_name: mq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes: 
      - type: volume
        source: logs
        target: /var/log/rabbitmq
    
  poleval:
    build: ./src
    container_name: poleval
    environment: 
      MQURL: amqp://mq:5672/%2f
      ESHOST: elastic.kubasikora.rocks
      ESPORT: 80
    depends_on: 
      - mq
      - elasticsearch
    
volumes:
  esdata:
  logs:
